// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { TreeNode } from "./TreeNode";

/**
 * A container node that splits its space among children.
 *
 * Fills the assigned area along its [`Direction`], drawing resize handles
 * between children. A Branch with one child renders that child at full size
 * with no split chrome.
 *
 * # Fields
 *
 * - `id`: [`Uuid`] - Unique identifier for this Branch
 * - `direction`: [`Direction`] - The direction along which children are laid out (horizontal or vertical)
 * - `children`: Vec<[`TreeNode`]> - Child nodes in order. 0..N children
 * - `ratios`: Vec<f32> - Relative sizes for each child. Must match `children.len()` when active
 */
export type Branch = { 
/**
 * Unique identifier for this Branch
 */
id: string, 
/**
 * The direction along which children are laid out (horizontal or vertical)
 */
direction: Direction, 
/**
 * Child nodes in order. 0..N children
 */
children: Array<TreeNode>, 
/**
 * Relative sizes for each child. Must match `children.len()` when active
 */
ratios: Array<number>, };
