// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The direction along which a [`Branch`] lays out its children.
 *
 * # Variants
 *
 * - [`Horizontal`](Direction::Horizontal): Children are laid out side-by-side,
 * left to right
 * - [`Vertical`](Direction::Vertical): Children are laid out top-to-bottom
 */
export type Direction = "Horizontal" | "Vertical";
