// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectFile } from "./ProjectFile";

/**
 * The `flight_meta` model. Maps to the `flight_meta` table in the `.flight`
 * SQLite database.
 *
 * # Fields
 *
 * - `id`: [`String`] - UUID identifying this Flight (stored as TEXT in SQLite)
 * - `name`: [`String`] - Human-readable name given by the user
 * - `created_at`: [`i64`] - Unix epoch seconds when this Flight was created
 * - `updated_at`: [`i64`] - Unix epoch seconds when this Flight was last modified
 * - `files`: [`Vec<ProjectFile>`](ProjectFile) - List of files associated with this Flight
 */
export type FlightMetadata = { 
/**
 * UUID identifying this Flight (stored as TEXT in SQLite)
 */
id: string, 
/**
 * Human-readable name given by the user
 */
name: string, 
/**
 * Unix epoch seconds when this Flight was created
 */
created_at: bigint, 
/**
 * Unix epoch seconds when this Flight was last modified
 */
updated_at: bigint, 
/**
 * List of files associated with this Flight
 */
files: Array<ProjectFile>, };
