// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Flight is the top-level container — the folder that contains everything related to one
 * specific writing project.
 *
 * # Fields
 *
 * - `id`: [Uuid] - The unique identifier for the Flight.
 * - `name`: [String] - The name given by the user to the Flight.
 * - `created_at`: [DateTime<Utc>] - The time the Flight was created.
 * - `updated_at`: [DateTime<Utc>] - The time the Flight was last updated.
 * - `is_favorite`: [bool] - Whether this Flight is favourited by the user.
 *
 * TODO: Develop better documentation for Flight struct
 */
export type Flight = { 
/**
 * Unique identifier for the Flight
 */
id: string, 
/**
 * A name given by the user to the Flight
 */
name: string, 
/**
 * The time the Flight was created
 */
created_at: string, 
/**
 * The time the Flight was last updated
 */
updated_at: string, 
/**
 * Whether this Flight is favourited by the user
 */
is_favorite: boolean, };
