// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetType } from "./WidgetType";

/**
 * A leaf node representing a Widget instance at a position in the Workspace tree.
 *
 * # Fields
 *
 * - `id`: [`Uuid`] - Unique identifier for this Leaf
 * - `widget_type`: [`WidgetType`] - The type of widget this leaf holds
 * - `widget_instance_id`: Option<[`Uuid`]> - Which specific document or context this widget displays
 *
 *     - Editor widgets: the UUID of the Rachis being edited
 *     - Notes widgets: the UUID of the note being viewed
 *     - Picker/Empty widgets: `None`
 */
export type Leaf = { 
/**
 * Unique identifier for this Leaf
 */
id: string, 
/**
 * The type of widget this leaf holds
 */
widget_type: WidgetType, 
/**
 * Which specific document or context this widget displays
 *
 * - Editor widgets: the UUID of the Rachis being edited
 * - Notes widgets: the UUID of the note being viewed
 * - Picker/Empty widgets: `None`
 */
widget_instance_id: string | null, };
