// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `files` model. Serves as an index of every content file in the project directory.
 */
export type ProjectFile = { 
/**
 * UUID identifying this file in the `.flight` database (stable across renames)
 */
id: string, 
/**
 * Relative path from the project root, e.g. `"chapters/Chapter 2.rachis"`
 */
path: string, 
/**
 * Display title of the file (derived from filename or user-set)
 */
title: string, 
/**
 * Entity type, if this file represents a story entity.
 * `None` (NULL) for non-entity files like chapter drafts.
 */
entity_type: string | null, 
/**
 * Cached word count for the file
 */
word_count: number, 
/**
 * Unix epoch seconds of the last file modification time
 */
last_modified: bigint, 
/**
 * Whether this is a `.rachis` native file (true) or an imported format (false)
 */
is_native: boolean, };
