// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the result of reconciling a single Flight entry.
 */
export type ReconcileStatus = { "type": "Found" } | { "type": "Moved", "data": { 
/**
 * The old path where the Flight was found.
 */
old_path: string, 
/**
 * The new path where the Flight was found.
 */
new_path: string, } } | { "type": "Mismatch", "data": { 
/**
 * The cached path where the conflicting `.flight` was found.
 */
path: string, 
/**
 * The UUID of the Flight currently at this location.
 */
mismatched_id: string | null, } } | { "type": "Discovered", "data": { 
/**
 * The directory path where the `.flight` was found.
 */
path: string, 
/**
 * The UUID of the discovered Flight.
 */
flight_id: string, } };
