// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReconcileStatus } from "./ReconcileStatus";

/**
 * Report for one Flight entry after a reconciliation pass.
 */
export type ReconcileReport = { 
/**
 * The UUID of the Flight that was reconciled.
 */
id: string, 
/**
 * The human-readable name of the Flight.
 */
name: string, 
/**
 * What happened during reconciliation.
 */
status: ReconcileStatus, };
