// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistryEntry } from "./RegistryEntry";

/**
 * A lightweight registry that tracks all known Flights.
 *
 * This is a **pure data model**: mutations modify data in memory only.
 * No file I/O happens here. Persistence is handled separately by
 * [load_from_disk] and [save_to_disk].
 *
 * # Validation
 *
 * Call [validate()](Registry::validate) to check structural integrity:
 * - All UUIDs are valid and unique
 * - All names are non-empty
 * - All paths are non-empty
 * - No duplicate paths
 */
export type Registry = {
    /**
     * Schema version for future migration support
     */
    version: number;
    /**
     * The list of registered Flights
     */
    flights: Array<RegistryEntry>;
};
