// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update for a `RegistryEntry`. `None` fields are left unchanged.
 */
export type RegistryEntryPatch = { 
/**
 * New display name (and thus new `.flight` filename).
 * When set, the caller is responsible for renaming the `.flight` file on disk.
 */
name: string | null, 
/**
 * New path to the enveloping directory.
 * When set, the caller is responsible for updating scan paths.
 */
path: string | null, 
/**
 * Set the favourite status explicitly (not toggled).
 * `true` = favourited, `false` = unfavourited, `None` = unchanged.
 */
is_favorite: boolean | null, 
/**
 * Set `last_opened_at` to right now.
 */
bump_last_opened: boolean, 
/**
 * New cached word count.
 */
word_count: number | null, };
