// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry in the Flight registry.
 */
export type RegistryEntry = { 
/**
 * Unique identifier for this Flight
 */
id: string, 
/**
 * Human-readable name for the Flight
 */
name: string, 
/**
 * Absolute path to the `.rachis` database file
 */
path: string, 
/**
 * Whether this Flight is marked as a favourite
 */
is_favorite: boolean, 
/**
 * When this Flight was last opened by the user
 */
last_opened_at: string, 
/**
 * When this Flight was first created
 */
created_at: string, 
/**
 * Cached total word count across all Rachises in this Flight
 */
word_count: number, };
