// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A path that the Registry can use to verify itself.
 */
export type ScanPath = { 
/**
 * The path to scan for `.flight` files
 */
path: string, };
