// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Branch } from "./Branch";
import type { Leaf } from "./Leaf";

/**
 * A node in the Workspace tree, either a [`Branch`] or a [`Leaf`].
 *
 * - [`Branch`]: Splits its space among child nodes along a direction.
 * - [`Leaf`]: A widget instance at a position in the tree.
 */
export type TreeNode = { "Branch": Branch } | { "Leaf": Leaf };
