// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeNode } from "./TreeNode";

/**
 * The root of a Workspace tree. Always has exactly one root node.
 *
 * # Fields
 *
 * - `root`: [`TreeNode`] - The root of the Workspace tree.
 */
export type Tree = { 
/**
 * The root of the Workspace tree.
 */
root: TreeNode, };
