// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of widget displayed inside a [`Leaf`].
 *
 * # Variants
 *
 * - [`Editor`](WidgetType::Editor): The area in which users may write their story
 * - [`Outline`](WidgetType::Outline): A document structure view
 * - [`Notes`](WidgetType::Notes): Author annotations and notes attached to the Flight and/or its Rachises
 * - [`Story`](WidgetType::Story): High-level story metadata and progress tracking
 * - [`Tags`](WidgetType::Tags): An overview of all tags present in the Flight
 * - [`Picker`](WidgetType::Picker): A placeholder shown when no widget type has been selected yet.
 * - [`Empty`](WidgetType::Empty): Displays a picker menu for the user to choose a widget type.
 */
export enum WidgetType { "Editor" = "Editor", "Outline" = "Outline", "Notes" = "Notes", "Story" = "Story", "Tags" = "Tags", "Picker" = "Picker", "Empty" = "Empty" }
