[package]
name = "rachis"
version = "0.6.0"
description = "Rachis Writing: Desktop App"
authors = ["AAILMeNTT"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "rachis_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono = { version = "^0.4.45", features = ["serde"] }
regex = "1.13.1"
rusqlite = { version = "^0.40.1", features = ["bundled"] }
serde = { version = "^1.0.229", features = ["derive"] }
serde_json = { version = "^1.0.151" }
tauri = { version = "^2.11.5", features = [] }
tauri-plugin-opener = { version = "^2.5.4" }
ts-rs = { version = "^12.0.1", features = ["chrono-impl", "uuid-impl"] }
uuid = { version = "^1.24.0", features = ["v4"] }
walkdir = "2.5.0"

[dev-dependencies]
proptest = { version = "^1.11.0" }
