// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Flight is the top-level container — the folder that contains everything related to one
 * specific writing project.
 *
 * # Fields
 *
 * * `id` - The unique identifier for the Flight.
 * * `name` - The name given by the user to the Flight.
 * * `created_at` - The time the Flight was created.
 * * `updated_at` - The time the Flight was last updated.
 *
 * TODO: Develop better documentation for Flight struct
 */
export type Flight = { 
/**
 * Unique identifier for the Flight
 */
id: string, 
/**
 * A name given by the user to the Flight
 */
name: string, 
/**
 * The time the Flight was created
 */
created_at: string, 
/**
 * The time the Flight was last updated
 */
updated_at: string, };
