// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the types of Rachises that may exist.
 * Rachis types come in primarily two groups: Generic Rachises and Entity Rachises.
 * Generic Rachis types are more meta and describe the story itself, while Entity Rachises
 * define some recognisable entity in the story.
 *
 * # Types
 *
 * * [RachisType::Act](RachisType::Act) - An Act Rachis. Conceptualised as the largest unit of the story, encapsulating multiple arcs.
 * * [RachisType::Arc](RachisType::Arc) - An Arc Rachis. Conceptualised as a collection of Scenes and comprise a character's journey through the story.
 * * [RachisType::Scene](RachisType::Scene) - A Scene Rachis. Conceptualised as a specific event or moment during the story.
 * * [RachisType::Default](RachisType::Default) - A default Rachis
 * * [RachisType::Character](RachisType::Character) - A Character Rachis. Conceptualised as a specific person, character, or otherwise entity in the story.
 * * [RachisType::Event](RachisType::Event) - An Event Rachis. Conceptualised as a specific happenstance in the story.
 * * [RachisType::Location](RachisType::Location) - A Location Rachis. Conceptualised as a specific place or area in the story.
 * * [RachisType::Item](RachisType::Item) - An Item Rachis. Conceptualised as a specific object or thing in the story.
 * * [RachisType::Note](RachisType::Note) - A Note Rachis. Conceptualised as a author-level commentary or note on the story.
 */
export type RachisType = "Act" | "Arc" | "Scene" | "Default" | "Character" | "Event" | "Location" | "Item" | "Note";
